// <auto-generated />
using ACoreBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACoreBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ACoreBackend.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstMidName = "Albert1",
                            LastName = "Nosteen1"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstMidName = "Albert2",
                            LastName = "Nosteen2"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstMidName = "Albert3",
                            LastName = "Nosteen3"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstMidName = "Albert4",
                            LastName = "Nosteen4"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstMidName = "Albert5",
                            LastName = "Nosteen5"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstMidName = "Albert6",
                            LastName = "Nosteen6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
